var mongoose        = require('mongoose')
   ,validate        = require('mongoose-validator')
   ,validator       = require('validator') 
   ,uniqueValidator = require('mongoose-unique-validator')
   ,Schema          = mongoose.Schema;

var CurrencySchema = new Schema({
  short_name:      {type: String, unique: true, required: "can't be blank"},
  long_name:       {type: String, required: "can't be blank"},
  valid:           {type: Boolean, default: true}
});

CurrencySchema.virtual('country_code').get(function () {
  return this.short_name.substring(0,2).toLowerCase();
});

CurrencySchema.statics = {  
getCurrencies: function (cb) {  
	cb({ 
  USD: 'United_States_Dollar',
  EUR: 'Euro',
  GBP: 'British_Pound',
  AUD: 'Australian_Dollar',
  CAD: 'Canadian_Dollar',
  SEK: 'Swedish_Krona',
  CHF: 'Swiss_Franc',
  TRY: 'Turkish_Lira',
  BTC: 'Bitcoin',
  XAU: 'Gold (troy ounce)',
  XAG: 'Silver (troy ounce)',
  AFN: 'Afghan_Afghani',
  ALL: 'Albanian_Lek',
  DZD: 'Algerian_Dinar',
  AOA: 'Angolan_Kwanza',
  ARS: 'Argentine_Peso',
  AMD: 'Armenian_Dram',
  AWG: 'Aruban_Florin',  
  AZN: 'Azerbaijani_Manat',
  BSD: 'Bahamian_Dollar',
  BHD: 'Bahraini_Dinar',
  BDT: 'Bangladeshi_Taka',
  BBD: 'Barbadian_Dollar',
  BYR: 'Belarusian_Ruble',
  BZD: 'Belize_Dollar',
  BMD: 'Bermudan_Dollar',
  BTN: 'Bhutanese_Ngultrum',
  BOB: 'Bolivian_Boliviano',
  BAM: 'Bosnia-Herzegovina',
  BWP: 'Botswanan_Pula',
  BRL: 'Brazilian_Real',
  BND: 'Brunei_Dollar',
  BGN: 'Bulgarian_Lev',
  BIF: 'Burundian_Franc',
  KHR: 'Cambodian_Riel',
  CVE: 'Cape_Verdean_Escudo',
  KYD: 'Cayman_Islands_Dollar',
  CLP: 'Chilean_Peso',
  CLF: 'Chilean_Unit',
  CNY: 'Chinese_Yuan',
  COP: 'Colombian_Peso',
  KMF: 'Comorian_Franc',
  CDF: 'Congolese_Franc',
  CRC: 'Costa_Rican_Colón',
  HRK: 'Croatian_Kuna',
  CUP: 'Cuban_Peso',
  CZK: 'Czech_Rep_Koruna',
  DKK: 'Danish_Krone',
  DJF: 'Djiboutian_Franc',
  DOP: 'Dominican_Peso',
  XCD: 'East_Caribbean_Dollar',
  EGP: 'Egyptian_Pound',
  ERN: 'Eritrean_Nakfa',
  EEK: 'Estonian_Kroon',
  ETB: 'Ethiopian_Birr',
  FKP: 'Falkland_Pound',
  FJD: 'Fijian_Dollar',
  GMD: 'Gambian_Dalasi',
  GEL: 'Georgian_Lari',
  GHS: 'Ghanaian_Cedi',
  GIP: 'Gibraltar_Pound',
  GTQ: 'Guatemalan_Quetzal',
  GGP: 'Guernsey_Pound',
  GNF: 'Guinean_Franc',
  GYD: 'Guyanaese_Dollar',
  HTG: 'Haitian_Gourde',
  HNL: 'Honduran_Lempira',
  HKD: 'Hong_Kong_Dollar',
  HUF: 'Hungarian_Forint',
  ISK: 'Icelandic_Króna',
  INR: 'Indian_Rupee',
  IDR: 'Indonesian_Rupiah',
  IRR: 'Iranian_Rial',
  IQD: 'Iraqi_Dinar',
  JMD: 'Jamaican_Dollar',
  JPY: 'Japanese_Yen',
  JEP: 'Jersey_Pound',
  JOD: 'Jordanian_Dinar',
  KZT: 'Kazakhstani_Tenge',
  KES: 'Kenyan_Shilling',
  KWD: 'Kuwaiti_Dinar',
  KGS: 'Kyrgystani_Som',
  LAK: 'Laotian_Kip',
  LVL: 'Latvian_Lats',
  LBP: 'Lebanese_Pound',
  LSL: 'Lesotho_Loti',
  LRD: 'Liberian_Dollar',
  LYD: 'Libyan_Dinar',
  LTL: 'Lithuanian_Litas',
  MOP: 'Macanese_Pataca',
  MKD: 'Macedonian_Denar',
  MGA: 'Malagasy_Ariary',
  MWK: 'Malawian_Kwacha',
  MYR: 'Malaysian_Ringgit',
  MVR: 'Maldivian_Rufiyaa',
  MTL: 'Maltese_Lira',
  IMP: 'Manx_pound',
  MRO: 'Mauritanian_Ouguiya',
  MUR: 'Mauritian_Rupee',
  MXN: 'Mexican_Peso',
  MDL: 'Moldovan_Leu',
  MNT: 'Mongolian_Tugrik',
  MAD: 'Moroccan_Dirham',
  MZN: 'Mozambican_Metical',
  MMK: 'Myanma_Kyat',
  NAD: 'Namibian_Dollar',
  NPR: 'Nepalese_Rupee',
  ANG: 'Netherlands_Guilder',
  TWD: 'New_Taiwan_Dollar',
  NZD: 'New_Zealand_Dollar',
  NIO: 'Nicaraguan_Córdoba',
  NGN: 'Nigerian_Naira',
  KPW: 'North_Korean_Won',
  NOK: 'Norwegian_Krone',
  OMR: 'Omani_Rial',
  PKR: 'Pakistani_Rupee',
  PAB: 'Panamanian_Balboa',
  PGK: 'Papua_Guinean_Kina',
  PYG: 'Paraguayan_Guarani',
  PEN: 'Peruvian_Nuevo_Sol',
  PHP: 'Philippine_Peso',
  PLN: 'Polish_Zloty',
  QAR: 'Qatari_Rial',
  RON: 'Romanian_Leu',
  RUB: 'Russian_Ruble',
  RWF: 'Rwandan_Franc',
  SHP: 'Saint_Helena_Pound',
  SVC: 'Salvadoran_Colón',
  WST: 'Samoan_Tala',
  SAR: 'Saudi_Riyal',
  RSD: 'Serbian_Dinar',
  SCR: 'Seychellois_Rupee',
  SLL: 'Sierra_Leonean_Leone',
  SGD: 'Singapore_Dollar',
  SBD: 'Solomon_Islands',
  SOS: 'Somali_Shilling',
  ZAR: 'South_African_Rand',
  KRW: 'South_Korean_Won',
  LKR: 'Sri_Lankan_Rupee',
  SDG: 'Sudanese_Pound',
  SRD: 'Surinamese_Dollar',
  SZL: 'Swazi_Lilangeni',
  SYP: 'Syrian_Pound',
  STD: 'São_Tomé',
  TJS: 'Tajikistani_Somoni',
  TZS: 'Tanzanian_Shilling',
  THB: 'Thai_Baht',
  TOP: 'Tongan_Paʻanga',
  TTD: 'Trinidad_Tobago_Dollar',
  TND: 'Tunisian_Dinar',
  TMT: 'Turkmenistani_Manat',
  UGX: 'Ugandan_Shilling',
  UAH: 'Ukrainian_Hryvnia',
  AED: 'UAE_Dirham',
  
  UYU: 'Uruguayan_Peso',
  UZS: 'Uzbekistan_Som',
  VUV: 'Vanuatu_Vatu',
  VEF: 'Venezuelan_Fuerte',
  VND: 'Vietnamese_Dong',
  YER: 'Yemeni_Rial',
  ZMW: 'Zambian_Kwacha',
  ZWL: 'Zimbabwean_Dollar'
 })
},
getLimitedCurrencies: function (cb) {  
  cb({ 
  USD: 'United States Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  AUD: 'Australian Dollar',
  CAD: 'Canadian Dollar',
  SEK: 'Swedish Krona',
  CHF: 'Swiss Franc',
  TRY: 'Turkish Lira'
 })
}
}
//   XDR: 'Special Drawing Rights'
/*
  ZMK: 'Zambian Kwacha (pre-2013)',

  XOF: 'CFA Franc BCEAO',
  XAF: 'CFA Franc BEAC',
  XPF: 'CFP Franc',
*/
CurrencySchema.plugin(uniqueValidator, { message: '{PATH} already in use.' })
mongoose.model('Currency', CurrencySchema);
